---
title: "02_lifeExpectancy_QW"
author: "Duc-Quang Nguyen"
date: "1 June 2016"
output: html_document
---

### Note about responsive SVG and explorer !!

Based on: http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/

* Add
`<div class="container"> before the inline SVG / graphic`

* Add this in the stylesheet: 

``.container {
    width: 100%;
    height: 0;
    padding-top: 99%;
    position: relative;
}
svg {
    position: absolute;
    top: 0;
    left: 0;
}
``

```{r setup, include=FALSE}
library(WDI)
library(dplyr)
library(tidyr)
library(htmltools)
library(swiTheme)

getData <- F
data.file <- "input/WB_lifeExpectancy.csv"
trad.file <- "input/Life Expectancy - Sheet1.csv"
```

```{r getData}
#### A) Using WB

if(getData) {
  data.dl <- WDI(
    indicator = 'SP.DYN.LE00.IN',
    start = 1950,  
    end = 2016, 
    extra = TRUE, 
    cache = NULL
  )
  colnames(data.dl)[3] <- 'value'

  data <- data.dl %>% select(-capital, -longitude, -latitude, -lending)
	write.csv(data, file = data.file, row.names = F)
} else {
  data <- read.csv( file = data.file )
}

txt <- read.csv(trad.file, row.names = 1, stringsAsFactors = F)
# discard incomplete translations
cidx <- unique(which(txt =="" | is.na(txt), T)[,2])
if(length(cidx > 0)) {
  warning(paste(colnames(txt)[cidx], collapse = "\t"), " languages will be discarded!", "\n")
  txt <- txt[,-cidx, drop = F]
}
colnames(txt)

```

## Life expectancy

```{r data wrangling for plot}
# interactive 
library(scales)
library(swiRcharts)
library(ggiraph)
library(swiMap)

strokeWidth <- 0.3

swi_iso2 <- c("CH", "CN", "RU", "BR", "IN", "JP", "EU", "ZQ", "ZG", "XU", "Z4")
countries.iso2 <- c(swi_iso2, c('RW', 'SL', 'KH'))

iso2.todiscard.manualPicked <- c(
  "AG", "AW", "BB", "BN", "BS", "DJ", "FM", "GD", 
  "GQ", "KG", "VC", "VI", "VC", "ST", "SB", "PF", 
  "KI", "BZ", "LC", "PG", "WS", "VU", "UZ", "TJ", 
  "TM", "TT", "TO", "TG", "SZ", "SK", "SI", "MU",
  "MR", "MG", "MD", "LS", "AZ", "DO", "GU", "ME",
  "EC"
  )

le <- data %>% arrange(year)

# get the main regions iso2
regions.all <- unique( le[!is.na(le$region) & (le$region == "Aggregates") ,"country"])
main.regions <- regions.all[grep("(all income levels|North America)", regions.all)]
regions.iso2 <- as.character(le[match(main.regions, le$country), 'iso2c'])

## Discard some of the data
# discard aggregates that are not regions.iso2 and world !
le <- le %>% filter(region != "Aggregates" | (region == "Aggregates") &
  iso2c %in% c("1W",regions.iso2))

# discard country with incomplete data
le.nrow <- le %>% group_by(iso2c, country, iso3c) %>% 
  dplyr::summarise(l = sum(!is.na(value))) %>% ungroup()
iso2.todiscard <- le.nrow %>% filter(l != max(l)) %>% 
  select(iso2c) %>% unlist(use.names = F) %>% as.character()

# discard countries where to SWI translation available
iso2.todiscard <- c(
  iso2.todiscard, 
  as.character(unique(le$iso2)[!unique(le$iso2) %in% countryTranslations[,"iso2"]]),
  iso2.todiscard.manualPicked 
)
le <- le %>% filter(!iso2c %in% iso2.todiscard)

# discard years with only NA
year.todiscard <- le %>% group_by(year) %>% dplyr::summarise( valid = sum(!is.na(value))) %>% ungroup() %>%
  filter(valid == 0) %>% select(year) %>% unlist(use.names = F)
if(length(year.todiscard) > 0) {
  le <- le %>% filter(!year %in% year.todiscard)
}
# rename "all income levels"
le$country <- gsub("\\(all income levels\\)$", "", le$country)

# Have a thicker line for the world average, aggregates
le$strokeWidth <- "A"
le[which(le$iso2c == "1W"),'strokeWidth'] <- "C"

# get only the countries, i.e. region is not "Aggregates" or NA
le[!is.na(le$region) & (le$iso2 %in% regions.iso2) ,'strokeWidth'] <- "B"
le$strokeWidth <- as.factor(le$strokeWidth)

# Have less alpha for aggregates and subset countries
le$alpha <- "A"
le[!is.na(le$region) & (le$iso2 %in% c("1W", countries.iso2, regions.iso2)) ,'alpha'] <- "B"
le$alpha <- as.factor(le$alpha)

## Define colors
le$color <- "A"
colors <- c(countries.iso2, regions.iso2)
names(colors) <- LETTERS[2:(length(colors)+1)]
cols <- names(colors)[match(le$iso2, colors)]
le[le$iso2 %in% colors ,'color']  <-  cols[!is.na(cols)]
le$color <- as.factor(le$color)

# compute the delta life expectancy
le <- le %>% group_by(iso2c, country, iso3c) %>% 
  dplyr::mutate(delta = round(last(value) - first(value), 1)) %>%
  dplyr::mutate(pc = round(((last(value) - first(value)) / first(value)) * 100)) %>% 
  dplyr::mutate(last = round(last(value), 1)) %>% 
  ungroup()

le %>% filter(country == "World")

```

```{r plot helper}

static_lineChart <- function(data, xaxisPadding = 14, label.font = "Open Sans Condensed") {
  
  maxYear <- max(data$year)
  minYear <- min(data$year)
  
  ggplot(data = dd) +  
    swi_theme(y_gridlines = F, base_size = 8, base_family = "Verdana") + 
    scale_x_continuous(breaks = seq(minYear, maxYear, 6), expand = c(0, 0), name = "",
                       limits = c(minYear, max = maxYear + xaxisPadding)) +
    ylab("") + 
    coord_fixed(ratio = 0.8) + 
    geom_path_interactive(
      aes(x = year, y = value, group = country, tooltip = tooltip, 
          data_id = dd$country, size = strokeWidth, alpha = alpha, colour = color)) + 
    scale_size_manual(values = c(strokeWidth, strokeWidth * 2.5,  strokeWidth * 6), guide=FALSE) +
    scale_alpha_manual(values = c(0.25, 0.7), guide=FALSE) +
    scale_color_manual(values = c("darkgrey", swi_rpal), guide=FALSE) +
    scale_fill_manual(values =  c("darkgrey", swi_rpal), guide=FALSE) +
    theme(
      legend.position = "none", 
      axis.line = element_blank(),
      axis.text = element_text(size = 12),
      axis.ticks.length=unit(2.5, "pt"),
      plot.margin = unit(c(-30, 0, -20, -3.5), "mm"),
      plot.title=element_text(margin=margin(rep(0, 4)))
    ) +
    labs(title = "", subtitle = NULL) +
    geom_text(data = subset(dd, iso2c %in% 
      c("1W", countries.iso2, regions.iso2) & year == maxYear),
              aes(x = year, y = value, group = country, 
                  color = color, label = as.character(country)),
              size = 3.2, family = label.font, nudge_x = 0.2, 
              nudge_y= 0.1, check_overlap = T, hjust = 0
    )
}

interactive_chart <- function(gpath, fontname = 'Open Sans Condensed') {
 ggiraph(
  code = {print(gpath)},
  hover_css = "stroke-opacity:0.99;stroke-width:1.5px;stroke:black;",
  tooltip_opacity = 0.7,
  pointsize = 15,
  width = "100%",
  height = "100%",
  height_svg = 7,
  width_svg = 7,
  fontname_sans = fontname,
  fontname_serif = fontname
) 
}



```

```{r plot by language}

for (lang in colnames(txt)) {
  dd <- le
  maxYear <- max(dd$year)
  minYear <- min(dd$year)
  
  fontname <- txt["typeface.svg", lang] # font ggplot2 svg
  dd$country <- countryTranslation(as.character(dd$iso2c), lang)[,2]
  dd$country <- gsub("'", "_", dd$country)
  
  dd$tooltip <- paste0("<b>", as.character(dd$country), "</b><br>",
              '<div><span style="font-size: 0.8em">',
              txt["h3", lang], " ", dd$last, " ", txt["tooltip.2", lang], 
              " ", maxYear, ", ",
              "+", dd$pc, "% ", txt["tooltip.3", lang], " ", minYear, "</span></div>")
  
  chart <- static_lineChart(dd, label.font = fontname)
  ichart <- interactive_chart(chart, fontname = fontname)
  
  footer <- paste0(
    txt['source', lang], ": ", htmlLink(txt['source.url', lang], txt['source.txt', lang]), " | ", txt['made.with', lang], 
    htmlLink(txt['made.with.url', lang], txt['made.with.name', lang]), " & ", 
    txt['inspired.by', lang], " ", htmlLink(txt['inspired.by.url', lang], 
    txt['inspired.by.name', lang]), " | ", htmlLink("http://www.swissinfo.ch", "swissinfo.ch"),
    " | ", htmlLink("https://twitter.com/duc_qn", "@duc_qn")
  )
  
  save_html(
    tags$html(
     tags$head(includeHTML("styles.html")),
      tags$body(    
      h2(txt["main.title", lang]),
      div(class = "descr", HTML(txt["subtitle1", lang])),
      h3(txt["h3", lang]),
      div(class="container",
        div(class="graphic", ichart)
      ),
      div(id = "footer", HTML(txt["caption", lang])),
      div(id = "cite", HTML(footer)),
      HTML('<script type="text/javascript" src="https://www.swissinfo.ch/static/Themes/basic/js/vendor/iframeResizer.contentWindow.3.5.3.min.js"></script>')  
    )), file = paste0("02_lifeExpectancy_interactiveLine_", lang, ".html")
  )
}

```


